language: node_js
node_js:
  - '12'
  - '14'
  - '16'
before_install:
  - npm install -g istanbul codecov
install:
  - npm install
script:
  - npm run build
  - istanbul cover ./node_modules/mocha/bin/_mocha tests --reporter lcovonly
  - codecov
